name: CI - Construir e Publicar Imagem Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      # =======================================================
      # PASSOS DE TESTE TEMPORARIAMENTE DESATIVADOS
      # O workflow irá pular esta seção.
      # =======================================================
      # - name: Configurar Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '18'
      #
      # - name: Instalar Dependências com 'npm ci'
      #   run: npm ci
      #   working-directory: ./Calculadora
      #
      # - name: Rodar Testes com 'npm test'
      #   run: npm test
      #   working-directory: ./Calculadora
      # =======================================================

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/calculadora-ci:latest