name: CI - Testar, Construir e Publicar Imagem Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      
      - name: Configurar Node.js e Rodar Testes
        uses: actions/setup-node@v4
        with:
          node-version: '18' 
      - name: Instalar Dependências
        run: npm install
      - name: Rodar Testes com Jest
        run: npm test
    

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/calculadora-ci:latest