name: CI - Testar, Construir e Publicar Imagem Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # PASSO 1: Baixar o código
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      # PASSO 2: Instalar o Node.js e o NPM
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # PASSO 3: Instalar as dependências do projeto
      - name: Instalar Dependências
        run: npm ci

      # PASSO 4: Rodar os testes
      - name: Rodar Testes com Jest
        run: npx test

      # PASSO 5: Fazer o login no Docker Hub (só acontece se os testes passarem)
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # PASSO 6: Construir e enviar a imagem
      - name: Build e Push da Imagem
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/calculadora-ci:latest